language: python
python:
  - "2.7"

install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov

script: coverage run --source=eppy  
                     --omit=eppy/tests/test_runner.py -m py.test -v

after_success:
    - codecov