environment:

  matrix:
    - PYTHON: "C:\\Python27"
      ARCHITECTURE: "i386"
    - PYTHON: "C:\\Python27-x64"
      ARCHITECTURE: "x86_64"
    - PYTHON: "C:\\Python35"
      ARCHITECTURE: "i386"
    - PYTHON: "C:\\Python35-x64"
      ARCHITECTURE: "x86_64"

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  # install EnergyPlus
  - ECHO "Installing EnergyPlus"
  - ps: $env:ENERGYPLUS_VERSION = "8.7.0"
  - ps: $env:ENERGYPLUS_TAG = "v8.7.0"
  - ps: $env:ENERGYPLUS_SHA = "78a111df4a"
  - ps: $env:ENERGYPLUS_INSTALL_VERSION = "8-7-0"
  - ps: $env:ENERGYPLUS_DOWNLOAD_BASE_URL = "https://github.com/NREL/EnergyPlus/releases/download/$env:ENERGYPLUS_TAG"
  - ps: $env:ENERGYPLUS_DOWNLOAD_FILENAME = "EnergyPlus-$env:ENERGYPLUS_VERSION-$env:ENERGYPLUS_SHA-Windows-$env:ARCHITECTURE.exe"
  - ps: $env:ENERGYPLUS_DOWNLOAD_URL = "$env:ENERGYPLUS_DOWNLOAD_BASE_URL/$env:ENERGYPLUS_DOWNLOAD_FILENAME"

  - ps: "curl $env:ENERGYPLUS_DOWNLOAD_URL -OutFile $env:TMP\\$env:ENERGYPLUS_DOWNLOAD_FILENAME"
  - ps: "& $env:TMP\\$env:ENERGYPLUS_DOWNLOAD_FILENAME /S | Out-Null"

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - ps: echo $env:PYTHON
  - "python -m pip install pytest"

  # set the integration test environment variable
  - "SET EPPY_INTEGRATION=TRUE"
  # install eppy
  - "python setup.py install"

build: off

test_script:
  # Test command.
  - "python -m pytest eppy -v"
